config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/mypage'  => 'home#mypage'
  get 'home/profile' => 'home#profile'
  get 'home/deliver_address'  => 'home#deliver_address'
  get 'home/logout'  => 'home#logout'
  get 'home/identification' => 'home#identification'
  get 'home/email_password' => 'home#email_password'
  get 'home/list_exhibit' => 'home#list_exhibit'
  get 'home/search' => 'home#search'
  get 'home/exhibit_product/:id' => 'home#exhibit_product'

  get 'home/card_create'  => 'home#card_create'
  get 'items/exhibit_product/:id' => 'itmes#exhibit_product'

  get 'home/card'  => 'home#card'
  delete  'home/:id'  => 'home#destroy'
  get 'items/category' => 'items#category'
  resources :items, only: [:new, :create, :edit, :update, :show] do
    resources :item_image, only: :create
    collection do
      get "get_category_children", defaults: {format: "json"}
      get "get_category_grandchildren", defaults: {format: "json"}
    end
  end
  resources :purchase, only: [:edit, :update]
  devise_for :users 
  get '/signup' => 'signup#index'
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3' # ここで 入力の全てが終了
      get 'done' # 登録完了後のページに遷移
    end
  end
  resources :credit_cards, only: :new
end

app/models/home.rb
class Home < ApplicationRecord
    # has_many :items
    # has_many :item_images
    has_ancestry
    enum condition: {brand_new: 0, near_unused: 1, no_noticeable_dirt: 2, somewhat_dirty: 3, dirty: 4, bad_condition: 5}
    enum delivery_schedule: {one_to_two_days: 0, two_to_three_days: 1, four_to_seven_days: 2}
    enum postage: {postage_included: 0, cash_on_delivery: 1}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @index_item = Item.all.order("id DESC").limit(10)
    @image = ItemImage.all.order("id DESC").limit(10)
    @item = Item.all
    @parents = Category.where(ancestry: nil)
  end

  def mypage
    @user = current_user
  end

  def profile
    @user = current_user
  end

  def deliver_address
    @user = current_user
  end

  def card_create
    @user = current_user
    # @credit_card = Credit_card.find(params[:id])
  end

  def card
    @user = current_user
    # @credit_card = Credit_card.find(params[:id])
  end

  def identification
    @user = current_user
  end

  def email_password
    @user = current_user
  end

  def identification
    @user = current_user
  end

  def logout
  end 

  

  def list_exhibit
    @item = Item.all.order("id DESC")
    # @image = ItemImage.all.order("id DESC")
  end

  def search
    @items = Item.where('name LIKE(?)', "%#{params[:keyword]}%")
    @item_count = Item.where('name LIKE(?)', "%#{params[:keyword]}%").count
    @key = params[:keyword]
    # @image = ItemImage.all
  end

  def exhibit_product
    @item = Item.find(params[:id])
    # @image = ItemImage.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to home_list_exhibit_path
  end

  private

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end

end

app/views/home/_camera.html.haml
-if user_signed_in?
  =link_to new_item_path, :class => "camera" do
    .camera-title 出品
    %i.fas.fa-camera.fa-3x

-else 
  =link_to signup_path, :class => "camera" do
    .camera-title 出品
    %i.fas.fa-camera.fa-3x

app/views/home/_footer.html.haml
%footer.footer
  %section.footer-above.clearfix
    .footer-above-container
      .footer-above-container__box
        %h2 スマホでかんたんフリマアプリ
        %p 今すぐ無料ダウンロード！
        .footer-above-container__box-banner
          =image_tag "http://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?575670517", :width => "68"
          =image_tag "http://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?575670517", :width => "133",:height => "40", class:"bannar-icon"
          =image_tag "http://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?575670517", :width => "133",:height => "40", class:"bannar-icon"
      =image_tag "http://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?575670517", :width => "300" , :class => "footer-above-container__image"
  %section.footer-under
    %nav.clearfix
      .footer-under__box
        %h2.footer-head メルカリについて
        %ul
          %li
            =link_to "会社概要（運営会社）"
          %li
            =link_to "採用情報"
          %li
            =link_to "プレスリリース"
          %li
            =link_to "公式ブログ"
          %li
            =link_to "メルカリロゴ利用ガイドライン"
          .font
          %li.footer-social-link
            =link_to "" do
              %i.fab.fa-twitter.fa-3x
          %li.footer-social-link
            =link_to "" do
              %i.fab.fa-facebook-square.fa-3x
      .footer-under__box
        %h2.footer-head ヘルプ＆ガイド
        %ul
          %li
            =link_to "メルカリガイド"
          %li
            =link_to "らくらくメルカリ便"
          %li
            =link_to "ゆうゆうメルカリ便"
          %li
            =link_to "大型メルカリ便"
          %li
            =link_to "車体取引ガイド"
          %li
            =link_to "メルカリあんしん・あんぜん宣言！"
          %li
            =link_to "偽ブランド品撲滅への取り組み"
          %li
            =link_to "メルカリボックス"
      .footer-under__box.footer-under__box--full-width
        %h2.footer-head プライバシーと利用規約
        .footer-under__box--inner-footer-cell
          %ul
            %li
              =link_to "プライバシーポリシー"
            %li
              =link_to "メルカリ利用規約"
            %li
              =link_to "あんしんスマホサポート制度に関する利用特約"
            %li
              =link_to "コンプライアンスポリシー"
        .footer-under__box--inner-footer-cell
          %ul
            %li
              =link_to "個人データの安全管理に係る基本方針"
            %li
              =link_to "特定商取引に関する表記"
            %li
              =link_to "資金決済法に基づく表示"
            %li
              =link_to "法令順守と犯罪抑止のために"
      .footer-under__box.footer-under__box--footer-nav-lang
        %h2.footer-head 国
        %ul
          %li
            =link_to "日本"
          %li
            =link_to "United States"
  .footer-bottom.clearfix
    =link_to image_tag("http://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?3951034907", :width => "124", :height => "33"), "#"
    %span.footer-bottom__copyright
      %p © 2019 Mercari

app/views/home/_header.html.haml
%header.clearfix
  .header__container
    .header__container-above
      =link_to image_tag('http://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?575670517',class: "img") , root_path
      = form_tag(home_search_path, :method => 'get') do
        = text_field_tag :search,'',:placeholder => "何かお探しですか？",class: "field",name:"keyword"
        %label
          %i.fas.fa-search
          = submit_tag 'Search', :name => nil , class: "search"
          
    
    .header__container-under
      .header__container-under--left
        %ul
          %li
            %i.fas.fa-list-ul
            =link_to 'カテゴリーから探す',items_category_path,class:".header__container-under--left-link"
          %li
            %i.fas.fa-tag
            =link_to 'ブランドから探す','#'
      .header__container-under--right
        .header__container-under--right-login
          -if user_signed_in?
            %ul
              %li
                =link_to 'マイページ',home_mypage_path 
              %li
                %i.fas.fa-check
                =link_to 'やることリスト','#'
              %li
                %i.far.fa-bell
                =link_to 'お知らせ','#'
          -else 
            %ul
              %li
                =link_to 'ログイン', new_user_session_path, class: "header_login_button"
                =link_to '新規会員登録', signup_path, class: "header_signup_button"   

app/views/home/_sidebar_item.html.haml
.main-contents__sidebar
  .main-contents__sidebar-mypage
    %ul
      %li
        %select.select-default{:name => "sort_order"}
          %option{:value => ""} 並び替え
          %option{:value => "price_asc"}
            価格の安い順
          %option{:value => "price_desc"}
            価格の高い順
          %option{:value => "created_asc"}
            出品の古い順
          %option{:value => "created_desc"}
            出品の新しい順
          %option{:value => "like_desc"}
            いいね!の多い順
        %i.fas.fa-chevron-right
      %li
        =link_to "お知らせ"
        %i.fas.fa-chevron-right
      %li
        =link_to "やることリスト"
        %i.fas.fa-chevron-right
      %li
        =link_to "いいね！一覧"
        %i.fas.fa-chevron-right
      %li
        =link_to "出品する", new_item_path
        %i.fas.fa-chevron-right
      %li
        =link_to "出品した商品 - 出品中", home_list_exhibit_path
        %i.fas.fa-chevron-right
      %li
        =link_to "出品した商品 - 取引中"
        %i.fas.fa-chevron-right
      %li
        =link_to "出品した商品 - 売却済み"
        %i.fas.fa-chevron-right
      %li
        =link_to "購入した商品 - 取引中"
        %i.fas.fa-chevron-right
      %li
        =link_to "購入した商品 - 過去の取引"
        %i.fas.fa-chevron-right
      %li
        =link_to "ニュース一覧"
        %i.fas.fa-chevron-right
      %li
        =link_to "評価一覧"
        %i.fas.fa-chevron-right
      %li
        =link_to "ガイド"
        %i.fas.fa-chevron-right
      %li
        =link_to "お問い合わせ"
        %i.fas.fa-chevron-right
  .main-contents__sidebar-merupay
    %h3 メルペイ
    %ul
      %li
        =link_to "売上・振込申請"
        %i.fas.fa-chevron-right
      %li
        =link_to "ポイント"
        %i.fas.fa-chevron-right
  .main-contents__sidebar-setting
    %h3 設定
    %ul
      %li
        =link_to "プロフィール", home_profile_path
        %i.fas.fa-chevron-right
      %li
        =link_to "発送元・お届け先住所変更", home_deliver_address_path
        %i.fas.fa-chevron-right
      %li
        =link_to "支払い方法", home_card_create_path
        %i.fas.fa-chevron-right
      %li
        =link_to "メール/パスワード"
        %i.fas.fa-chevron-right
      %li
        =link_to "本人情報", home_identification_path
        %i.fas.fa-chevron-right
      %li
        =link_to "電話番号の確認"
        %i.fas.fa-chevron-right
      %li
        =link_to "ログアウト", home_logout_path
        %i.fas.fa-chevron-right

app/views/home/card.html.haml
= render partial: "header"
- breadcrumb :profile
= breadcrumbs separator: " &rsaquo; " ,class: "breadcrumb"
.main
  .main-contents
    = render partial: "sidebar"
    .main-contents__right--back-card
      %h2　支払い方法
      .card-block1 
        %section
          %h3 クレジットカード一覧
          %li
            = image_tag "card-pre.png", class: "card-pre"
            -# .card-block1__form
            -# .card-block1__form__block
            -#   .card-block1__form__image
            -#   .card-block1__button
            -#   .card-block1__form__number
            -#   .card-block1__form__date


        .card-block2 支払い方法について ＞
  
= render partial: "footer"
= render partial: "camera"

app/views/home/card_create.html.haml
= render partial: "header"
- breadcrumb :identification
= breadcrumbs separator: " &rsaquo; ",class: "breadcrumb"
.main
  .main-contents
    = render partial: "sidebar"
    .main-contents__right--card_create
      %h2　クレジットカード情報入力
      .main-contents__right--identification-section
        .main-contents__right--identification-section-form
          %label カード番号
          .signup-form-require 必須
          %input{placeholder: "半角数字のみ"}
          = image_tag "credit-card-design.png", class: "credit-card-create_design" 
        
          %label 有効期限
          .signup-form-require 必須
          = form_for @user.prefecture, method: :post do |f|
            = f.select :prefecture, [["---", "---"],["01", "01"],["02", "02"],["03", "03"],["04", "04"],["05", "05"],["06", "06"],["07", "07"],["08", "08"],["09", "09"],["10", "10"],["11", "11"],["12", "12"]], {},  prompt: "---", class: "signup-main3__form__prefecture__select",selected: @user.prefecture 
            月

          -# = form_for @credit_card.month, method: :get do |f|
          -#   = f.select [["---", "---"],["01", "01"],["02", "02"],["03", "03"],["04", "04"],["05", "05"],["06", "06"],["07", "07"],["08", "08"],["09", "09"],["10", "10"],["11", "11"],["12", "12"]]


          = form_for @user.prefecture, method: :post do |f|
            = f.select :prefecture, [["---", "---"], ["19", "19"],["20", "20"],["21", "21"],["22", "22"],["23", "23"],["24", "24"],["25", "25"],["26", "26"],["27", "27"],["28", "28"],["29", "29"]], {},  prompt: "---", class: "signup-main3__form__prefecture__select",selected: @user.prefecture 
            年
        
          %label セキュリティコード
          .signup-form-require 必須
          %input{placeholder: "カード背面4桁もしくは3桁の番号"}
          .main-contents__right--identification-section-upload-about
            =link_to "カード裏面の番号とは？", class: "main-contents__right--identification-section-upload-about-in"


          
        .main-contents__right-item
          %p
            =link_to "追加する",home_card_path, class: "main-contents__right-item-registration"
        
    
= render partial: "footer"
= render partial: "camera"

app/views/home/deliver_address.html.haml
= render partial: "header"
- breadcrumb :identification
= breadcrumbs separator: " &rsaquo; ",class: "breadcrumb"
.main
  .main-contents
    = render partial: "sidebar"
    .main-contents__right--identification
      %h2　発送元・お届け先住所変更
      .main-contents__right--identification-section
        .main-contents__right--identification-section-form
          %label お名前
          %input{value: @user.last_name }
          %input{value: @user.first_name }

        .main-contents__right--identification-section-form
          %label お名前カナ
          %input{value: @user.last_name_kana }
          %input{value: @user.first_name_kana }

        .main-contents__right--identification-section-form
          %label 郵便番号
          %input{value: @user.zip }

        .main-contents__right--identification-section-form
          %label 都道府県
          = form_for @user.prefecture, method: :post do |f|
            = f.select :prefecture, [["---", "---"], ["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"], ["福島県", "福島県"], ["茨城県", "茨城県"], ["栃木県", "栃木県"], ["群馬県", "群馬県"], ["埼玉県", "埼玉県"], ["千葉県", "千葉県"], ["東京都", "東京都"], ["神奈川県", "神奈川県"], ["新潟県", "新潟県"], ["富山県", "富山県"], ["石川県", "石川県"], ["福井県", "福井県"], ["山梨県", "山梨県"], ["長野県", "長野県"], ["岐阜県", "岐阜県"], ["静岡県", "静岡県"], ["愛知県", "愛知県"], ["三重県", "三重県"], ["滋賀県", "滋賀県"], ["京都府", "京都府"], ["大阪府", "大阪府"], ["兵庫県", "兵庫県"], ["奈良県", "奈良県"], ["和歌山県", "和歌山県"], ["鳥取県", "鳥取県"], ["島根県", "島根県"], ["岡山県", "岡山県"], ["広島県", "広島県"], ["山口県", "山口県"], ["徳島県", "徳島県"], ["香川県", "香川県"], ["愛媛県", "愛媛県"], ["高知県", "高知県"], ["福岡県", "福岡県"], ["佐賀県", "佐賀県"], ["長崎県", "長崎県"], ["熊本県", "熊本県"], ["大分県", "大分県"], ["宮崎県", "宮崎県"], ["鹿児島県", "鹿児島県"], ["沖縄県", "沖縄県"]], {},  prompt: "---", class: "signup-main3__form__prefecture__select"



        .main-contents__right--identification-section-form
          %label 市町村
          %input{value: @user.city }

        .main-contents__right--identification-section-form
          %label 番地
          %input{value: @user.address }

        .main-contents__right--identification-section-form
          %label 建物
          %input{value: @user.building }

        .main-contents__right--identification-section-form
          %label 電話番号
          %input{value: @user.phone_number }
        
        .main-contents__right-item
          =link_to "変更する", home_mypage_path, class: "main-contents__right-item-registration"


= render partial: "footer"
= render partial: "camera"

app/views/home/email_password.html.haml
= render partial: "header"
- breadcrumb :identification
= breadcrumbs separator: " &rsaquo; ",class: "breadcrumb"
.main
  .main-contents
    = render partial: "sidebar"
    .main-contents__right--identification
      %h2　メール/パスワード
      .main-contents__right--identification-section
        .main-contents__right--identification-section-form
          %label メールアドレス
          %input{value: @user.email }

        .main-contents__right--identification-section-form
          %label 現在のパスワード
          %input{value: @user.password }

        .main-contents__right--identification-section-form
          %label 新しいパスワード
          %input{placeholder: '7文字以上'}

        .main-contents__right--identification-section-form
          %label 新しいパスワード確認
          %input{placeholder: '7文字以上'}

        .main-contents__right-item
          =link_to "変更する", home_mypage_path, class: "main-contents__right-item-registration"




= render partial: "footer"
= render partial: "camera"

app/views/home/exhibit_product.html.haml
= render partial: "home/header"
- breadcrumb :exhibit_product
= breadcrumbs separator: " &rsaquo; " ,class: "breadcrumb"
.main.result
  .main-contents
    .main-contents-exhibit_product
      %main.item-show-main
        %section.item-show-main__exhibit
          %h1.item-show-main__container--head
            = @item.name
          .item-show-main__container__info
            .item-show-main__container__info__image
              = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image--large"
              -if @item.transaction_condition == 2
                .sold
                  %p SOLD
              .item-show-main__container__info__image__small
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
                = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            %table.item-show-main__container__info__detail{border: "1"}
              %tr.item-show-main__container__info__detail__seller
                %th.item-show-main__container__info__detail__seller__head
                  出品者
                %td.item-show-main__container__info__detail__seller__data
                  = link_to "ユーザー", "#", class: "item-show-main__container__info__detail__seller__data--top"
                  .item-show-main__container__info__detail__seller__data--bottom
                    = fa_icon "grin", text: 1000
                    = fa_icon "meh", text: 1000
                    = fa_icon "frown", text: 1000
              %tr.item-show-main__container__info__detail__category
                %th.item-show-main__container__info__detail__category__head
                  カテゴリー
                %td.item-show-main__container__info__detail__category__data
                  %p
                    = link_to do
                      レディース
                    %br
                    = link_to do
                      >トップス
                    %br
                    = link_to do
                      >Tシャツ/カットソー(半袖/袖なし)
                      -# =@parents.children.children.name

              %tr.item-show-main__container__info__detail__brand
                %th.item-show-main__container__info__detail__brand__head
                  ブランド
                %td.item-show-main__container__info__detail__brand__data
                  = link_to item_path do
                    ディズニー

              %tr.item-show-main__container__info__detail__condition
                %th.item-show-main__container__info__detail__condition__head
                  商品の状態
                %td.item-show-main__container__info__detail__condition__data
                  新品、未使用

              %tr.item-show-main__container__info__detail__charge
                %th.item-show-main__container__info__detail__charge__head
                  配送料の負担
                %td.item-show-main__container__info__detail__charge__data
                  送料込み（出品者負担）

              %tr.item-show-main__container__info__detail__delivery
                %th.item-show-main__container__info__detail__delivery__head
                  配送の方法
                %td.item-show-main__container__info__detail__delivery__data
                  %p.item-show-main__container__info__detail__delivery__data--top らくらくメルカリ便
                  %span.item-show-main__container__info__detail__delivery__data--bottom 匿名配送

              %tr.item-show-main__container__info__detail__region
                %th.item-show-main__container__info__detail__region__head
                  発送元地域
                %td.item-show-main__container__info__detail__region__data
                  = link_to item_path do
                    北海道

              %tr.item-show-main__container__info__detail__shipping
                %th.item-show-main__container__info__detail__shipping__head
                  発送の目安
                %td.item-show-main__container__info__detail__shipping__data
                  1~2日で発送
          .item-show-main__container__price
            %span.item-show-main__container__price--left
              ¥
              =@item.price
            %span.item-show-main__container__price--center (税込)
            %span.item-show-main__container__price--right 送料込み
          
          .item-show-main__container__description-exhibit
            %p
            =@item.description

        %section.item-show-main__exhibit-button
          .item-show-main__comment-exhibit-button
            =link_to "商品の編集" ,edit_item_path, method: :get, class:"item-show-main__comment--button-exhibit item-show-main__comment--button-exhibit-red"
            %p or
            =link_to "出品を一旦停止する" ,"#", class:"item-show-main__comment--button-exhibit"
            =link_to "この商品を削除する" ,"/home/#{@item.id}", method: :delete, class:"item-show-main__comment--button-exhibit"

        %section.item-show-main__exhibit-button
          .item-show-main__comment-exhibit
            .item-show-main__comment--rule
              %p
                相手のことを考え丁寧なコメントを心がけましょう。
                %br 不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %textarea.item-show-main__comment--input
            %button.item-show-main__comment--button コメントする
          
= render partial: "home/footer"
  

app/views/home/identification.html.haml
= render partial: "header"
- breadcrumb :identification
= breadcrumbs separator: " &rsaquo; ",class: "breadcrumb"
.main
  .main-contents
    = render partial: "sidebar"
    .main-contents__right--identification
      %h2　本人情報の登録
      .main-contents__right--identification-section
        .main-contents__right--identification-section-upload
          %p お客さまの本人情報をご登録ください。登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
          .main-contents__right--identification-section-upload-about
            =link_to "本人確認書類のアップロードについて", class: "main-contents__right--identification-section-upload-about-in"
            %i.fas.fa-chevron-right
        .main-contents__right--identification-section-form
          %label お名前
          %p
            = @user.last_name
            = @user.first_name
        .main-contents__right--identification-section-form
          %label お名前カナ
          %p 
            = @user.last_name_kana
            = @user.first_name_kana
        .main-contents__right--identification-section-form
          %label 生年月日
          %p 
            = @user.year
            ,
            = @user.month
            ,
            = @user.day
        .main-contents__right--identification-section-form
          %label 郵便番号
          %span 任意
          %input{value: @user.zip }
        .main-contents__right--identification-section-form
          %label 都道府県
          %span 任意
          = form_for @user.prefecture, method: :post do |f|
            = f.select :prefecture, [["---", "---"], ["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"], ["福島県", "福島県"], ["茨城県", "茨城県"], ["栃木県", "栃木県"], ["群馬県", "群馬県"], ["埼玉県", "埼玉県"], ["千葉県", "千葉県"], ["東京都", "東京都"], ["神奈川県", "神奈川県"], ["新潟県", "新潟県"], ["富山県", "富山県"], ["石川県", "石川県"], ["福井県", "福井県"], ["山梨県", "山梨県"], ["長野県", "長野県"], ["岐阜県", "岐阜県"], ["静岡県", "静岡県"], ["愛知県", "愛知県"], ["三重県", "三重県"], ["滋賀県", "滋賀県"], ["京都府", "京都府"], ["大阪府", "大阪府"], ["兵庫県", "兵庫県"], ["奈良県", "奈良県"], ["和歌山県", "和歌山県"], ["鳥取県", "鳥取県"], ["島根県", "島根県"], ["岡山県", "岡山県"], ["広島県", "広島県"], ["山口県", "山口県"], ["徳島県", "徳島県"], ["香川県", "香川県"], ["愛媛県", "愛媛県"], ["高知県", "高知県"], ["福岡県", "福岡県"], ["佐賀県", "佐賀県"], ["長崎県", "長崎県"], ["熊本県", "熊本県"], ["大分県", "大分県"], ["宮崎県", "宮崎県"], ["鹿児島県", "鹿児島県"], ["沖縄県", "沖縄県"]], {},  prompt: "---", class: "signup-main3__form__prefecture__select",selected: @user.prefecture


          -# =form_for Prefecture.name do |f|
          -#   = f.collection_select(:prefecture_id, Prefecture.all, :id, :name)
        .main-contents__right--identification-section-form
          %label 市区町村
          %span 任意
          %input{value: @user.city }
        .main-contents__right--identification-section-form
          %label 番地
          %span 任意
          %input{value: @user.address }
        .main-contents__right--identification-section-form
          %label 建物名
          %span 任意
          %input{value: @user.building }
        .main-contents__right-item
          %p
            =link_to "登録する",home_mypage_path, class: "main-contents__right-item-registration"
        .main-contents__right--identification-section-upload-about
          =link_to "本人情報の登録について", class: "main-contents__right--identification-section-upload-about-in"
          %i.fas.fa-chevron-right
= render partial: "footer"
= render partial: "camera"