config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/mypage'  => 'home#mypage'
  get 'home/profile' => 'home#profile'
  get 'home/deliver_address'  => 'home#deliver_address'
  get 'home/logout'  => 'home#logout'
  get 'home/identification' => 'home#identification'
  get 'home/email_password' => 'home#email_password'
  get 'home/list_exhibit' => 'home#list_exhibit'
  get 'home/search' => 'home#search'
  get 'home/exhibit_product/:id' => 'home#exhibit_product'

  get 'home/card_create'  => 'home#card_create'
  get 'items/exhibit_product/:id' => 'itmes#exhibit_product'

  get 'home/card'  => 'home#card'
  delete  'home/:id'  => 'home#destroy'
  get 'items/category' => 'items#category'
  resources :items, only: [:new, :create, :edit, :update, :show] do
    resources :item_image, only: :create
    collection do
      get "get_category_children", defaults: {format: "json"}
      get "get_category_grandchildren", defaults: {format: "json"}
    end
  end
  resources :purchase, only: [:edit, :update]
  devise_for :users 
  get '/signup' => 'signup#index'
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3' # ここで 入力の全てが終了
      get 'done' # 登録完了後のページに遷移
    end
  end
  resources :credit_cards, only: :new
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  
  def edit
    @user = User.find_by(id: current_user.id)
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(transaction_condition: 2, buyer_id: current_user.id)
      redirect_to root_path
    else
      redirect_to edit_path
    end
  end

  private

  def item_params
    params.require(:item).permit(
      :name,
      :price).merge(set_during_trading).merge(buyer_id: current_user.id)
  end

  def set_during_trading
    {transaction_condition: 2}
  end

end

app/views/purchase/edit.html.haml
.purchase-wrapper
  = render partial: "items/header"
  %main.purchase-main
    %h2.purchase-main__head
      購入内容の確認
    .purchase-main__detail
      .purchase-main__detail__container
        .purchase-main__detail__container__title
          = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg"
          %p
            = @item.name
        %p.purchase-main__detail__container__price
          ¥
          = @item.price
          %span 送料込み
        %p.purchase-main__detail__container__point ポイントはありません
        .purchase-main__detail__container__pay
          %span.purchase-main__detail__container__pay--title
            支払い金額
          %span.purchase-main__detail__container__pay--price
            ¥
            = @item.price
        = link_to "購入する", purchase_path, method: "patch", class: "purchase-main__detail__container__button"
    .purchase-main__delivery-info
      .purchase-main__delivery-info__container
        .purchase-main__delivery-info__container__detail
          %h3.purchase-main__delivery-info__container__detail--title
            配送先
          %p.purchase-main__delivery-info__container__detail--address
            〒
            = @user.zip
            %br
              = @user.prefecture
              = @user.city
              = @user.address
              = @user.building
            %span
              = @user.last_name
              = @user.first_name
        = link_to "変更する ＞", root_path, class: "purchase-main__delivery-info__container--change"
    .purchase-main__method
      .purchase-main__method__container
        %h3.purchase-main__method__container--title
          支払い方法
        %p.purchase-main__method__container--info-text
          ************7777
          %br 09/19
        = image_tag "visa.svg", class: "purchase-main__method__container--image"
        %p.purchase-main__method__container--change
          = link_to "変更する ＞", root_path
  = render partial: "items/footer"
    

app/views/purchase/new.html.haml
.purchase-wrapper
  = render partial: "items/header"
  %main.purchase-main
    %h2.purchase-main__head
      購入内容の確認
    .purchase-main__detail
      .purchase-main__detail__container
        .purchase-main__detail__container__title
          = image_tag "m59627988225_1.jpg"
          %p COACH コーチ ショルダーバッグ
        %p.purchase-main__detail__container__price
          ¥
          = @item.price
          %span 送料込み
        %p.purchase-main__detail__container__point ポイントはありません
        .purchase-main__detail__container__pay
          %span.purchase-main__detail__container__pay--title
            支払い金額
          %span.purchase-main__detail__container__pay--price
            ¥
            = @item.price
        = link_to "購入する", new_purchase_path, class: "purchase-main__detail__container__button"
    .purchase-main__delivery-info
      .purchase-main__delivery-info__container
        .purchase-main__delivery-info__container__detail
          %h3.purchase-main__delivery-info__container__detail--title
            配送先
          %p.purchase-main__delivery-info__container__detail--address
            〒
            = @user.zip
            %br
              = @user.prefecture
              = @user.city
              = @user.address
              = @user.building
            %span
              = @user.last_name
              = @user.first_name
        = link_to "変更する ＞", new_purchase_path, class: "purchase-main__delivery-info__container--change"
    .purchase-main__method
      .purchase-main__method__container
        %h3.purchase-main__method__container--title
          支払い方法
        %p.purchase-main__method__container--info-text
          ************7777
          %br 09/19
        = image_tag "visa.svg", class: "purchase-main__method__container--image"
        %p.purchase-main__method__container--change
          = link_to "変更する ＞", new_purchase_path
  = render partial: "items/footer"
    