config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/mypage'  => 'home#mypage'
  get 'home/profile' => 'home#profile'
  get 'home/deliver_address'  => 'home#deliver_address'
  get 'home/logout'  => 'home#logout'
  get 'home/identification' => 'home#identification'
  get 'home/email_password' => 'home#email_password'
  get 'home/list_exhibit' => 'home#list_exhibit'
  get 'home/search' => 'home#search'
  get 'home/exhibit_product/:id' => 'home#exhibit_product'

  get 'home/card_create'  => 'home#card_create'
  get 'items/exhibit_product/:id' => 'itmes#exhibit_product'

  get 'home/card'  => 'home#card'
  delete  'home/:id'  => 'home#destroy'
  get 'items/category' => 'items#category'
  resources :items, only: [:new, :create, :edit, :update, :show] do
    resources :item_image, only: :create
    collection do
      get "get_category_children", defaults: {format: "json"}
      get "get_category_grandchildren", defaults: {format: "json"}
    end
  end
  resources :purchase, only: [:edit, :update]
  devise_for :users 
  get '/signup' => 'signup#index'
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3' # ここで 入力の全てが終了
      get 'done' # 登録完了後のページに遷移
    end
  end
  resources :credit_cards, only: :new
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images
  # belongs_to :category
  enum condition: {brand_new: 0, near_unused: 1, no_noticeable_dirt: 2, somewhat_dirty: 3, dirty: 4, bad_condition: 5}
  enum delivery_schedule: {one_to_two_days: 0, two_to_three_days: 1, four_to_seven_days: 2}
  enum postage: {postage_included: 0, cash_on_delivery: 1}
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    
    @item = Item.new
    @item.item_images.build
    @category_parent_array = Category.where(ancestry: nil)
  end

  def get_category_children
    @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    # @item = Item.new(item_params)
    # @item.save
    # binding.pry
    # ItemImage.create(item_id: @item.id, image: image_params)
    # redirect_to root_path
    @item = Item.new(item_params)
    @item.save
    # @item.item_images.create(item_id: current_user.id, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-WZ8C7WkQNDWIFJnZ8A_mH2aTE1tYLPnsNp5KOSudh3rHX4CTyA")
    redirect_to root_path
  end

  def show
    @item = Item.find(params[:id])
    # @image = ItemImage.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @category_parent_array = Category.where(ancestry: nil)
    # @image = ItemImage.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    # @item.update(params_int(item_params))
    redirect_to "/home/exhibit_product/#{@item.id}"
  end

  private

  def image_params
    params.require(:item_images).permit(:image)
  end

  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :category_id,
      :condition,
      :postage,
      :region,
      :delivery_schedule,
      :price).merge(seller_id: current_user.id).merge(set_exhibit)
  end

  # def image_params
  #   params.require(:item_image).permit(images: []})
  # end
  
  def set_exhibit
    {transaction_condition: 1}
  end

end

app/views/items/_footer.html.haml
%footer.exhibit-footer
  %ul
    %li
      = link_to "プライバシーポリシー"
    %li
      = link_to "メルカリ利用規約"
    %li
      = link_to "特定取引に関する表記"
  .exhibit-footer__logo
    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?2531475304"
  %small © 2019 Mercari

app/views/items/_header.html.haml
%header.exhibit-header
  = link_to root_path do {class: "exhibit-header__logo"}
    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3312594182"

app/views/items/category.html.haml
= render partial: "home/header"
.bread
  - breadcrumb :mypage
  = breadcrumbs separator: " &rsaquo; ",class: "breadcrumb"
.main
  .main-contents
    .main-contents-category
      %h2 カテゴリー一覧
      %ul.main-contents-category-p
        - @parents.each do |parent|
          %li.main-contents-category-parents
            =link_to do
              =parent.name

      - @parents.each do |parent|
        %h3.main-contents-category-genre
          =parent.name
        .main-contents-category-container
          %ul.main-contents-category-list
            - parent.children.each do |child|
              %li.main-contents-category-list-child
                .main-contents-category-list-child-text=child.name
                .main-contents-category-list-g
                  - child.children.each do |grandchild|
                    .main-contents-category-list-grand
                      =link_to do
                        =grandchild.name
= render partial: "home/footer"
= render partial: "home/camera"

app/views/items/edit.html.haml
.exhibit-wrapper
  = render partial: "header"
  %main.exhibit-main
    .exhibit-main__head
      %h2 商品の情報を入力
    = form_for @item do |f|{class: "exhibit-main__image-content"}
      .exhibit-main__image-content__form
        = f.fields_for :item_images do |img|
          .exhibit-main__image-content__form--title
            %h3 出品画像
            %span
              必須
            %p 最大10枚までアップロードできます
          .exhibit-main__image-content__form__body
            .exhibit-main__image-content__form__body__img-small#img_field
            .exhibit-main__image-content__form__body__img-large
              = img.label :image, class: "exhibit-main__image-content__form__body__img-large--label", for: "file" do
                %h3
                  ドラッグアンドドロップ
                  %br またはクリックしてファイルをアップロード
              = img.file_field :image, id: "file", class: "exhibit-main__image-content__form__body--file", name: "item_images[image][]", accept: "image/*", multiple: true
      .exhibit-main__description
        .exhibit-main__description__title
          %label
            商品名
            %span 必須
          = f.text_field :name, placeholder: "商品名 (必須40字まで)", class: "exhibit-main__description__title__input"
        .exhibit-main__description__body
          %label
            商品の説明
            %span 必須
          = f.text_area :description, placeholder: "商品の説明 (必須1,000文字以内) (色、素材、重さ、定価、注意点など) 例)2010年頃に1万円で購入してジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "exhibit-main__description__body__input"
      .exhibit-main__detail
        %h3.exhibit-main__detail__title
          商品の詳細
        .exhibit-main__detail__input
          .exhibit-main__detail__input__category#category-box
            %label
              カテゴリー
              %span 必須
            = f.collection_select :category_id, @category_parent_array, :id, :name, {prompt: "---"}, id: "parent-form", name: "item[category_id]"
          .exhibit-main__detail__input__state
            %label
              商品の状態
              %span 必須
            = f.select :condition, Item.conditions.keys.map {|k| [I18n.t("enums.item.condition.#{k}"), k]}, prompt: "---"
      .exhibit-main__delivery-info
        %h3.exhibit-main__delivery-info__title
          配送について
          = link_to "?", ""
        .exhibit-main__delivery-info__input
          .exhibit-main__delivery-info__input__fee
            %label
              配送料の負担
              %span 必須
            = f.select :postage, Item.postages.keys.map {|k| [I18n.t("enums.item.postage.#{k}"), k]}, prompt: "---"
          .exhibit-main__delivery-info__input__area
            %label
              発送元の地域
              %span 必須
            = f.collection_select :region, Prefecture.all, :id, :name, prompt: "---"
          .exhibit-main__delivery-info__input__shipping-days
            %label
              発送までの日数
              %span 必須
            = f.select :delivery_schedule, Item.delivery_schedules.keys.map {|k| [I18n.t("enums.item.delivery_schedule.#{k}"), k]}, prompt: "---"
      .exhibit-main__sell-price
        %h3.exhibit-main__sell-price__title
          販売価格(300〜9,999,999)
          = link_to "?", ""
        .exhibit-main__sell-price__body
          .exhibit-main__sell-price__body__label
            %label
              価格
              %span 必須
            %p.exhibit-main__sell-price__body__label__input
              ¥
              = f.text_field :price, placeholder: "例)  300", id: "exhibit-price"
          .exhibit-main__sell-price__body__fee
            %p 販売手数料(10%)
            %p.exhibit-main__sell-price__body__fee__calc -
          .exhibit-main__sell-price__body__gain
            %p 販売利益
            %p.exhibit-main__sell-price__body__gain__calc -
      .exhibit-main__foot
        %p.exhibit-main__foot__rules
          = link_to "禁止されている出品"
          、
          = link_to "行為"
          を必ずご確認ください。
          %br
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to "偽ブランドの販売"
          は
          %br
          犯罪であり処罰される可能性があります。
          %br
          また、出品をもちまして加盟店規約に同意したことになります。
        .exhibit-main__foot__btn
          = f.submit "出品する",  class: "exhibit-main__foot__btn--decision"
          = link_to "もどる", root_path, class: "exhibit-main__foot__btn--back"
  = render partial: "footer"

-# .exhibit-wrapper
-#   = render partial: "header"
-#   %main.exhibit-main
-#     .exhibit-main__head
-#       %h2 商品の情報を入力
-#     = form_for @item do |f|{class: "exhibit-main__image-content"}
-#       .exhibit-main__image-content__form
-#         = f.fields_for :item_images  do |img|
-#           .exhibit-main__image-content__form--title
-#             %h3 出品画像
-#             %span
-#               必須
-#             %p 最大10枚までアップロードできます
-#           .exhibit-main__image-content__form__body
-#             .exhibit-main__image-content__form__body__img-small#img_field
-#             .exhibit-main__image-content__form__body__img-large
-#               = img.label :image, class: "exhibit-main__image-content__form__body__img-large--label", for: "file" do
-#                 %h3
-#                   ドラッグアンドドロップ
-#                   %br またはクリックしてファイルをアップロード
-#             = img.file_field :image, id: "file", class: "exhibit-main__image-content__form__body--file", name: "item_images[image][]", accept: "image/*", multiple: true
-#       .exhibit-main__description
-#         .exhibit-main__description__title
-#           %label
-#             商品名
-#             %span 必須
-#           = f.text_field :name, placeholder: "商品名 (必須40字まで)", class: "exhibit-main__description__title__input"
-#         .exhibit-main__description__body
-#           %label
-#             商品の説明
-#             %span 必須
-#           = f.text_area :description, placeholder: "商品の説明 (必須1,000文字以内) (色、素材、重さ、定価、注意点など) 例)2010年頃に1万円で購入してジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "exhibit-main__description__body__input"
-#       .exhibit-main__detail
-#         %h3.exhibit-main__detail__title
-#           商品の詳細
-#         .exhibit-main__detail__input
-#           .exhibit-main__detail__input__category#category-box
-#             %label
-#               カテゴリー
-#               %span 必須
-#             = f.select :category_id, @category_parent_array, {}, {id: "parent-form"}
-#           .exhibit-main__detail__input__state
-#             %label
-#               商品の状態
-#               %span 必須
-#             = f.select :condition, Item.conditions.keys.map {|k| [I18n.t("enums.item.condition.#{k}"), k]}, prompt: "---"
-#       .exhibit-main__delivery-info
-#         %h3.exhibit-main__delivery-info__title
-#           配送について
-#           = link_to "?", ""
-#         .exhibit-main__delivery-info__input
-#           .exhibit-main__delivery-info__input__fee
-#             %label
-#               配送料の負担
-#               %span 必須
-#             = f.select :postage, Item.postages.keys.map {|k| [I18n.t("enums.item.postage.#{k}"), k]}, prompt: "---"
-#           .exhibit-main__delivery-info__input__area
-#             %label
-#               発送元の地域
-#               %span 必須
-#             = f.collection_select :region, Prefecture.all, :id, :name, prompt: "---"
-#           .exhibit-main__delivery-info__input__shipping-days
-#             %label
-#               発送までの日数
-#               %span 必須
-#             = f.select :delivery_schedule, Item.delivery_schedules.keys.map {|k| [I18n.t("enums.item.delivery_schedule.#{k}"), k]}, prompt: "---"
-#       .exhibit-main__sell-price
-#         %h3.exhibit-main__sell-price__title
-#           販売価格(300〜9,999,999)
-#           = link_to "?", ""
-#         .exhibit-main__sell-price__body
-#           .exhibit-main__sell-price__body__label
-#             %label
-#               価格
-#               %span 必須
-#             %p.exhibit-main__sell-price__body__label__input
-#               ¥
-#               = f.text_field :price, placeholder: "例)  300", id: "exhibit-price"
-#           .exhibit-main__sell-price__body__fee
-#             %p 販売手数料(10%)
-#             %p.exhibit-main__sell-price__body__fee__calc -
-#           .exhibit-main__sell-price__body__gain
-#             %p 販売利益
-#             %p.exhibit-main__sell-price__body__gain__calc -
-#       .exhibit-main__foot
-#         %p.exhibit-main__foot__rules
-#           = link_to "禁止されている出品"
-#           、
-#           = link_to "行為"
-#           を必ずご確認ください。
-#           %br
-#           またブランド品でシリアルナンバー等がある場合はご記載ください。
-#           = link_to "偽ブランドの販売"
-#           は
-#           %br
-#           犯罪であり処罰される可能性があります。
-#           %br
-#           また、出品をもちまして加盟店規約に同意したことになります。
-#         .exhibit-main__foot__btn
-#           = f.submit "出品する",  class: "exhibit-main__foot__btn--decision"
-#           = link_to "もどる", root_path, class: "exhibit-main__foot__btn--back"
-#   = render partial: "footer"

app/views/items/purchase.html.haml
.purchase-wrapper
  = render partial: "items/header"
  %main.purchase-main
    -# %section.purchase-main
    %h2.purchase-main__head
      購入内容の確認
    .purchase-main__detail
      .purchase-main__detail__container
        .purchase-main__detail__container__title
          = image_tag "m59627988225_1.jpg"
          %p COACH コーチ ショルダーバッグ
        %p.purchase-main__detail__container__price
          ¥4,500
          %span 送料込み
        %p.purchase-main__detail__container__point ポイントはありません
        .purchase-main__detail__container__pay
          %span.purchase-main__detail__container__pay--title
            支払い金額
          %span.purchase-main__detail__container__pay--price
            ¥4,500
        = link_to "購入する", purchase_items_path, class: "purchase-main__detail__container__button"
    .purchase-main__delivery-info
      .purchase-main__delivery-info__container
        .purchase-main__delivery-info__container__detail
          %h3.purchase-main__delivery-info__container__detail--title
            配送先
          %p.purchase-main__delivery-info__container__detail--address
            〒123-4567
            %br 愛知県◯◯市◯◯ ◯◯-◯◯
            %span 愛知太郎
        -# .purchase-main__delivery-info__contanier--change
        -#   %p
        = link_to "変更する ＞", purchase_items_path, class: "purchase-main__delivery-info__container--change"
    .purchase-main__method
      .purchase-main__method__container
        %h3.purchase-main__method__container--title
          支払い方法
        %p.purchase-main__method__container--info-text
          ************7777
          %br 09/19
        = image_tag "visa.svg", class: "purchase-main__method__container--image"
        %p.purchase-main__method__container--change
          = link_to "変更する ＞", purchase_items_path
  = render partial: "items/footer"
    

app/views/items/show.html.haml
.item-show-wrapper
  = render partial: "home/header"
  %main.item-show-main
    %section.item-show-main__container
      %h1.item-show-main__container--head
      = @item.name
      .item-show-main__container__info
        .item-show-main__container__info__image
          = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image--large"
          -if @item.transaction_condition == 2
            .sold
              %p SOLD
          .item-show-main__container__info__image__small
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
            = image_tag "https://i.pinimg.com/originals/11/80/c3/1180c317f8306d4fed8ca722393bc384.jpg", class: "item-show-main__container__info__image__small__upload"
        %table.item-show-main__container__info__detail{border: "1"}
          %tr.item-show-main__container__info__detail__seller
            %th.item-show-main__container__info__detail__seller__head
              出品者
            %td.item-show-main__container__info__detail__seller__data
              = link_to "ユーザー", item_path, class: "item-show-main__container__info__detail__seller__data--top"
              .item-show-main__container__info__detail__seller__data--bottom
                = fa_icon "grin", text: 1000
                = fa_icon "meh", text: 1000
                = fa_icon "frown", text: 1000
          %tr.item-show-main__container__info__detail__category
            %th.item-show-main__container__info__detail__category__head
              カテゴリー
            %td.item-show-main__container__info__detail__category__data
              %p
                = link_to do
                  レディース
                %br
                = link_to do
                  >トップス
                %br
                = link_to do
                  >Tシャツ/カットソー(半袖/袖なし)

          %tr.item-show-main__container__info__detail__brand
            %th.item-show-main__container__info__detail__brand__head
              ブランド
            %td.item-show-main__container__info__detail__brand__data
              = link_to item_path do
                ディズニー

          %tr.item-show-main__container__info__detail__condition
            %th.item-show-main__container__info__detail__condition__head
              商品の状態
            %td.item-show-main__container__info__detail__condition__data
              新品、未使用

          %tr.item-show-main__container__info__detail__charge
            %th.item-show-main__container__info__detail__charge__head
              配送料の負担
            %td.item-show-main__container__info__detail__charge__data
              送料込み（出品者負担）

          %tr.item-show-main__container__info__detail__delivery
            %th.item-show-main__container__info__detail__delivery__head
              配送の方法
            %td.item-show-main__container__info__detail__delivery__data
              %p.item-show-main__container__info__detail__delivery__data--top らくらくメルカリ便
              %span.item-show-main__container__info__detail__delivery__data--bottom 匿名配送

          %tr.item-show-main__container__info__detail__region
            %th.item-show-main__container__info__detail__region__head
              発送元地域
            %td.item-show-main__container__info__detail__region__data
              = link_to item_path do
                北海道

          %tr.item-show-main__container__info__detail__shipping
            %th.item-show-main__container__info__detail__shipping__head
              発送の目安
            %td.item-show-main__container__info__detail__shipping__data
              1~2日で発送
      .item-show-main__container__price
        %span.item-show-main__container__price--left
          ¥
          =@item.price
        %span.item-show-main__container__price--center (税込)
        %span.item-show-main__container__price--right 送料込み
      .item-show-main__container__move
        = link_to "購入画面に進む", edit_purchase_path
      .item-show-main__container__description
        %p
          =@item.description
      .item-show-main__container__bottom
        .item-show-main__container__bottom__left
          .item-show-main__container__bottom__left--good
            = fa_icon "heart"
            %span いいね！
            %span 100
          .item-show-main__container__bottom__left--report
            = fa_icon "flag"
            %span 不適切な商品の報告
        .item-show-main__container__bottom__right
          = link_to item_path do
            = fa_icon "lock"
            %span あんしん・あんぜんへの取り組み

    .item-show-main__comment
      .item-show-main__comment--rule
        %p
          相手のことを考え丁寧なコメントを心がけましょう。
          %br 不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %textarea.item-show-main__comment--input
      %button.item-show-main__comment--button コメントする

    .item-show-main__change
      = link_to "＜ 戻る"
      = link_to "進む ＞"
    .item-show-main__sns
      .item-show-main__sns__container
        = link_to item_path do
          %i.fab.fa-facebook-square
        = link_to item_path do
          %i.fab.fa-twitter-square
        = link_to item_path do
          %i.fab.fa-line
        = link_to item_path do
          %i.fab.fa-pinterest-square
    %section.item-show-main__profile
      .item-show-main__profile__self-exhibit
        = link_to "ユーザーさんのその他の出品", item_path
      .item-show-main__profile__image
        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

      .item-show-main__profile__relation
        = link_to "コーチのショルダーバッグその他の商品", item_path
      .item-show-main__profile__image
        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

        .item-show-main__profile__image__container
          = image_tag "m59627988225_1.jpg", class: "item-show-main__profile__image__container--detail"
          .item-show-main__profile__image__container__info
            %h3 商品名
            .item-show-main__profile__image__container__info__price-good
              %span.item-show-main__profile__image__container__info__price-good--value
                ¥4,500
              .item-show-main__profile__image__container__info__price-good--heart
                = fa_icon "heart"
                %span 100

    .item-show-main__bread-crumbs
      %p メルカリ ＞ COACH

  = render partial: "home/footer"